package com.devnexa.global.modules.admin;

import com.devnexa.global.modules.payment.Invoice;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class PdfExportService {

    public byte[] generateInvoicePdf(Invoice invoice) throws DocumentException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, out);
        document.open();

        // Header
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24);
        titleFont.setColor(0, 100, 200);
        Paragraph title = new Paragraph("INVOICE", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);
        document.add(new Paragraph(" "));

        // Invoice Details
        Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);
        Font valueFont = FontFactory.getFont(FontFactory.HELVETICA, 11);

        document.add(new Paragraph("Invoice Number: " + invoice.getInvoiceNumber(), labelFont));
        document.add(new Paragraph("Status: " + invoice.getStatus().name(), valueFont));
        document.add(new Paragraph("Amount: $" + String.format("%.2f", invoice.getAmount()), valueFont));
        if (invoice.getIssueDate() != null) {
            document.add(new Paragraph("Issue Date: " + invoice.getIssueDate().format(DateTimeFormatter.ISO_LOCAL_DATE), valueFont));
        }
        if (invoice.getDueDate() != null) {
            document.add(new Paragraph("Due Date: " + invoice.getDueDate().format(DateTimeFormatter.ISO_LOCAL_DATE), valueFont));
        }
        document.add(new Paragraph(" "));

        // Project info
        if (invoice.getProject() != null) {
            document.add(new Paragraph("Project: " + invoice.getProject().getTitle(), labelFont));
        }

        document.add(new Paragraph(" "));
        Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9);
        footerFont.setColor(150, 150, 150);
        document.add(new Paragraph("Generated by DevNexa Global — devnexa.global", footerFont));

        document.close();
        return out.toByteArray();
    }
}
